/**
 * Email validation and bot/disposable filtering utility
 * Blocks disposable email addresses, automated bot patterns, and malformed email inputs.
 */

// Comprehensive blacklist of temporary, burner, disposable, and automated mail providers
const DISPOSABLE_DOMAINS = new Set([
  '10minutemail.com',
  '10minutemail.net',
  '10minutemail.org',
  '10minmail.com',
  '20minutemail.com',
  '20minutemail.it',
  'airmail.news',
  'anonaddy.com',
  'anonaddy.me',
  'armyspy.com',
  'binkmail.com',
  'bobmail.info',
  'burnermail.io',
  'byom.de',
  'chacuo.net',
  'crazymailing.com',
  'cuvox.de',
  'dayrep.com',
  'disposablemail.com',
  'dispostable.com',
  'dropmail.me',
  'emailondeck.com',
  'emailfake.com',
  'einrot.com',
  'fakemailgenerator.com',
  'fleckens.hu',
  'generator.email',
  'getairmail.com',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.de',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'harakirimail.com',
  'inboxkitten.com',
  'inboxbear.com',
  'internxt.com',
  'jourrapide.com',
  'maildrop.cc',
  'mailinator.com',
  'mailinator.net',
  'mailinator2.com',
  'mailcatch.com',
  'mailnesia.com',
  'mailsac.com',
  'meltmail.com',
  'minuteinbox.com',
  'mohmal.com',
  'mohmal.in',
  'mytrashmail.com',
  'mytemp.email',
  'nada.ltd',
  'nada.email',
  'owlymail.com',
  'pokemail.net',
  'postinbox.com',
  'rhyta.com',
  'sharklasers.com',
  'spam4.me',
  'spambog.com',
  'spamevader.com',
  'spammotel.com',
  'superrito.com',
  'teleworm.us',
  'tempail.com',
  'tempmail.com',
  'tempmail.net',
  'tempmail.org',
  'temp-mail.org',
  'temp-mail.io',
  'temp-mail.de',
  'tempmailaddress.com',
  'throwawaymail.com',
  'throwaway.email',
  'tmail.ws',
  'trashmail.com',
  'trashmail.net',
  'trashmail.org',
  'trashmail.me',
  'yopmail.com',
  'yopmail.net',
  'yopmail.fr',
  'zeroe.ml'
]);

export interface EmailValidationResult {
  isValid: boolean;
  error?: string;
}

export function validateEmail(rawEmail: string): EmailValidationResult {
  const email = (rawEmail || '').trim().toLowerCase();

  if (!email) {
    return { isValid: false, error: 'Email address cannot be empty.' };
  }

  // Length limits
  if (email.length < 5 || email.length > 254) {
    return { isValid: false, error: 'Email address length must be between 5 and 254 characters.' };
  }

  // RFC 5322 strict pattern check
  const emailRegex = /^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/;
  if (!emailRegex.test(email)) {
    return { isValid: false, error: 'Please enter a valid email address (e.g. user@example.com).' };
  }

  // Disallow consecutive dots or leading/trailing dots in username
  const [username, domain] = email.split('@');
  if (!username || !domain) {
    return { isValid: false, error: 'Invalid email address format.' };
  }

  if (username.includes('..') || domain.includes('..')) {
    return { isValid: false, error: 'Email cannot contain consecutive dots.' };
  }

  // Domain must contain a valid TLD (at least 2 characters)
  const domainParts = domain.split('.');
  const tld = domainParts[domainParts.length - 1];
  if (!tld || tld.length < 2 || !/^[a-z]+$/.test(tld)) {
    return { isValid: false, error: 'Email must contain a valid top-level domain (e.g. .com, .org).' };
  }

  // Check against disposable / temporary email domains
  if (DISPOSABLE_DOMAINS.has(domain)) {
    return {
      isValid: false,
      error: 'Disposable and temporary email addresses are not permitted. Please use a legitimate email account.'
    };
  }

  // Check subdomains of disposable providers (e.g. *.mailinator.com)
  for (const blocked of DISPOSABLE_DOMAINS) {
    if (domain.endsWith('.' + blocked)) {
      return {
        isValid: false,
        error: 'Disposable and temporary email addresses are not permitted. Please use a legitimate email account.'
      };
    }
  }

  // Filter automated AI / Bot patterns
  // Examples: bot12345@, ai_test_839@, autogenerated-xyz@, long random hex strings
  const botPrefixes = ['bot_', 'ai_bot', 'automated_', 'crawler_', 'spam_test_', 'fake_mail_'];
  if (botPrefixes.some(prefix => username.startsWith(prefix))) {
    return {
      isValid: false,
      error: 'Automated bot email addresses are not allowed. Please use your personal or work email.'
    };
  }

  // Pure random hexadecimal usernames with 16+ chars (typical AI scraper/bot generator)
  if (/^[0-9a-f]{16,}$/.test(username)) {
    return {
      isValid: false,
      error: 'Automated or machine-generated email patterns are prohibited.'
    };
  }

  return { isValid: true };
}
